CREATE TABLE NILS_TRANSLATION(
  ID INT PRIMARY KEY,  
  NLS_LOCALE VARCHAR(10) NOT NULL,
  NLS_KEY VARCHAR(255) NOT NULL,
  NLS_VALUE VARCHAR(255) NOT NULL
);

INSERT INTO NILS_TRANSLATION VALUES(1, '', 'translate.me', 'I''m translated!');
INSERT INTO NILS_TRANSLATION VALUES(2, '', 'translate.get', 'Get from {0} to {1} from file.');
INSERT INTO NILS_TRANSLATION VALUES(3, '', 'translate.fallback', 'I''m a fallback!');
INSERT INTO NILS_TRANSLATION VALUES(4, '', 'deep.deepkey3', 'Key 3');
INSERT INTO NILS_TRANSLATION VALUES(5, '', 'deep.deeper.deeperkey4', 'Key 4');
INSERT INTO NILS_TRANSLATION VALUES(6, 'de', 'translate.me', 'Ich bin übersetzt!');

CREATE SCHEMA IF NOT EXISTS NILS;
CREATE TABLE NILS.NILS_TRANSLATION(
  ID INT PRIMARY KEY,  
  NLS_LOCALE VARCHAR(10) NOT NULL,
  NLS_KEY VARCHAR(255) NOT NULL,
  NLS_VALUE VARCHAR(255) NOT NULL
);
INSERT INTO NILS.NILS_TRANSLATION VALUES(1, '', 'translate.me', 'I''m translated!');

CREATE TABLE TRANSLATIONS(
  ID INT PRIMARY KEY,  
  THE_LOCALE VARCHAR(10) NOT NULL,
  THE_KEY VARCHAR(255) NOT NULL,
  THE_VALUE VARCHAR(255) NOT NULL
);
INSERT INTO TRANSLATIONS VALUES(1, '', 'translate.me', 'I''m translated!');
